FROM arm64v8/postgres:13

RUN apt-get update \
    && apt-get install -y postgis postgresql-13-postgis-3 \
    && rm -rf /var/lib/apt/lists/*

RUN echo "CREATE EXTENSION postgis;" > /docker-entrypoint-initdb.d/enable_postgis.sql
